# Generated by Django 3.1 on 2021-01-05 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coil_number', models.CharField(max_length=50)),
                ('coil_gauge', models.IntegerField(choices=[(32, 32), (30, 30), (28, 28), (26, 26), (24, 24), (22, 22), (20, 20)])),
                ('coil_width', models.IntegerField(choices=[(1220, 1220), (975, 975), (960, 960), (487, 487), (462, 462), (320, 320)])),
                ('coil_colour', models.CharField(choices=[('Dark Green', 'Dark Green'), ('Potters Clay', 'Potters Clay'), ('Tile Red', 'Tile Red'), ('Brick Red', 'Brick Red'), ('Maroon', 'Maroon'), ('Zincal', 'Zincal'), ('Service Grey', 'Service Grey'), ('Galvanized Iron', 'Galvanized Iron'), ('Avocado', 'Avocado'), ('Lagoon', 'Lagoon'), ('Sky Blue', 'Sky Blue'), ('Charcoal Black', 'Charcoal Black'), ('Chocolate', 'Chocolate')], max_length=50)),
                ('coil_finish', models.CharField(choices=[('Matt', 'Matt'), ('Plain', 'Plain')], max_length=50)),
                ('initial_mass', models.IntegerField()),
                ('initial_running_meters', models.IntegerField()),
                ('date_received', models.DateTimeField(default=datetime.datetime(2021, 1, 5, 16, 32, 26, 40620))),
            ],
        ),
    ]
