# Generated by Django 3.1 on 2021-01-05 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coil',
            name='coil_status',
            field=models.CharField(choices=[('New', 'New'), ('Baby coil', 'Baby Coil'), ('Finished', 'Finished')], default='undefined', max_length=50),
        ),
        migrations.AddField(
            model_name='coil',
            name='location',
            field=models.CharField(choices=[('Bond', 'Bond'), ('Production', 'Production')], default='not assigned', max_length=50),
        ),
        migrations.AlterField(
            model_name='coil',
            name='date_received',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 5, 16, 42, 43, 427807)),
        ),
    ]
