# Generated by Django 3.1 on 2021-01-05 13:46

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0002_auto_20210105_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='coil',
            name='production_transfer_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coil',
            name='date_received',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 5, 16, 46, 7, 515036)),
        ),
    ]
