# Generated by Django 3.1 on 2021-01-10 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0005_auto_20210110_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='coil',
            name='final_mass',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coil',
            name='date_received',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 10, 13, 15, 11, 821560)),
        ),
        migrations.AlterField(
            model_name='coil',
            name='production_transfer_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 10, 13, 15, 11, 821560)),
        ),
    ]
