# Generated by Django 3.1.7 on 2021-03-06 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0019_auto_20210302_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coil',
            name='date_received',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 19, 34, 39, 81598)),
        ),
        migrations.AlterField(
            model_name='coil',
            name='production_transfer_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 19, 34, 39, 81598)),
        ),
    ]
