# Generated by Django 3.1.1 on 2020-09-27 07:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_slug', models.SlugField(unique=True)),
                ('production_type', models.CharField(choices=[('WO', 'Work Order'), ('STD', 'Standard')], max_length=30)),
                ('production_bond', models.CharField(choices=[('Local', 'Local Bond'), ('Export', 'Export/ MUB')], max_length=50)),
                ('profile', models.CharField(choices=[('CMAX', 'Covermax'), ('MAXCV', 'MaxCover'), ('IT4', 'IT4'), ('TDK', 'Tekdek'), ('VT5', 'Versatile'), ('RT5', 'Romantile'), ('NC', 'Normal Corrugation'), ('PS', 'Plain Sheets'), ('NR', 'Normal Ridge'), ('VR', 'Versatile Ridge'), ('RR', 'Romantile Ridge')], max_length=50)),
                ('order_number', models.CharField(max_length=50)),
                ('order_colour', models.CharField(choices=[('DG', 'Dark Green'), ('PTC', 'Potters Clay'), ('TR', 'Tile Red'), ('BR', 'Brick Red'), ('MR', 'Maroon'), ('AZ', 'Zincal'), ('SVG', 'Service Grey'), ('GI', 'Galvanized Iron'), ('AV', 'Avocado'), ('LG', 'Lagoon'), ('SB', 'Sky Blue'), ('BLK', 'Charcoal Black'), ('CHOC', 'Chocolate')], max_length=50)),
                ('order_finish', models.CharField(max_length=10)),
                ('order_gauge', models.IntegerField()),
                ('order_width', models.IntegerField()),
                ('date_received', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['date_received', '-profile'],
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_length', models.DecimalField(decimal_places=2, max_digits=4)),
                ('prime_pieces', models.IntegerField()),
                ('reject_pieces', models.IntegerField()),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.order')),
            ],
            options={
                'ordering': ['-order_number', 'piece_length'],
            },
        ),
    ]
