# Generated by Django 3.1.1 on 2020-09-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piece',
            options={'ordering': ['-order_slug', 'piece_length']},
        ),
        migrations.RenameField(
            model_name='piece',
            old_name='order_number',
            new_name='order_slug',
        ),
    ]
