# Generated by Django 3.1.1 on 2020-10-01 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_auto_20200929_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coil_number', models.CharField(max_length=50)),
                ('coil_gauge', models.IntegerField()),
                ('coil_width', models.IntegerField()),
                ('coil_colour', models.CharField(max_length=50)),
                ('coil_finish', models.CharField(max_length=10)),
                ('initial_mass', models.IntegerField()),
                ('initial_running_meters', models.IntegerField()),
                ('date_received', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['coil_colour', 'coil_finish', 'coil_gauge', '-coil_width'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='order_finish',
            field=models.CharField(choices=[('Matt', 'Matt'), ('Plain', 'Plain')], max_length=10),
        ),
    ]
