# Generated by Django 3.1.1 on 2020-10-01 13:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20201001_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoilUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coil_number', models.CharField(max_length=50)),
                ('coil_gauge', models.IntegerField()),
                ('coil_width', models.IntegerField()),
                ('coil_colour', models.CharField(max_length=50)),
                ('coil_finish', models.CharField(max_length=10)),
                ('initial_mass', models.IntegerField()),
                ('Balance_mass', models.IntegerField()),
                ('cut_running_meters', models.IntegerField()),
                ('date_received', models.DateTimeField(default=datetime.datetime.now)),
                ('coil_slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.order')),
            ],
        ),
    ]
