# Generated by Django 3.1.1 on 2020-10-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_coilusage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoilUsage',
        ),
    ]
