# Generated by Django 3.1.1 on 2020-10-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_delete_coilusage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piece',
            options={'ordering': ['-order', 'piece_length']},
        ),
        migrations.RenameField(
            model_name='piece',
            old_name='order_slug',
            new_name='order',
        ),
    ]
