# Generated by Django 3.1.1 on 2020-10-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_auto_20201002_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_colour',
            field=models.CharField(choices=[('Dark Green', 'Dark Green'), ('Potters Clay', 'Potters Clay'), ('Tile Red', 'Tile Red'), ('Brick Red', 'Brick Red'), ('Maroon', 'Maroon'), ('Zincal', 'Zincal'), ('Service Grey', 'Service Grey'), ('Galvanized Iron', 'Galvanized Iron'), ('Avocado', 'Avocado'), ('Lagoon', 'Lagoon'), ('Sky Blue', 'Sky Blue'), ('Charcoal Black', 'Charcoal Black'), ('Chocolate', 'Chocolate')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='production_type',
            field=models.CharField(choices=[('Work Order', 'Work Order'), ('Standard', 'Standard')], max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='profile',
            field=models.CharField(choices=[('Covermax', 'Covermax'), ('Maxcover', 'Maxcover'), ('IT4', 'IT4'), ('Tekdek', 'Tekdek'), ('Versatile', 'Versatile'), ('Romantile', 'Romantile'), ('Normal Corrugation', 'Normal Corrugation'), ('Plain Sheet', 'Plain Sheet'), ('Normal Ridge', 'Normal Ridge'), ('Versatile', 'Versatile Ridge'), ('Romantile', 'Romantile Ridge')], max_length=50),
        ),
    ]
