# Generated by Django 3.1.1 on 2020-11-02 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20201003_2158'),
        ('production', '0008_auto_20201011_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='machine',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.machine'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_gauge',
            field=models.IntegerField(choices=[(32, 32), (30, 30), (28, 28), (26, 26), (24, 24), (22, 22), (20, 20)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='production_bond',
            field=models.CharField(choices=[('Local', 'Local'), ('Export', 'Export')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='profile',
            field=models.CharField(choices=[('Covermax', 'Covermax'), ('Maxcover', 'Maxcover'), ('IT4', 'IT4'), ('Tekdek', 'Tekdek'), ('Versatile', 'Versatile'), ('Romantile', 'Romantile'), ('Normal Corrugation', 'Normal Corrugation'), ('Plain Sheet', 'Plain Sheet'), ('Normal Ridge', 'Normal Ridge'), ('Versatile Ridge', 'Versatile Ridge'), ('Romantile Ridge', 'Romantile Ridge')], max_length=50),
        ),
    ]
