# Generated by Django 3.1.1 on 2020-11-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_cut_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='cut_material',
            name='coil_colour',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cut_material',
            name='coil_finish',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cut_material',
            name='coil_gauge',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cut_material',
            name='coil_width',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
