# Generated by Django 3.1.1 on 2020-11-03 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_cut_material_date_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='coil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='production.cut_material'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cut_material',
            name='new_or_used',
            field=models.BooleanField(default=True),
        ),
    ]
