# Generated by Django 3.1 on 2020-11-25 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_auto_20201103_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut_material',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.order'),
        ),
    ]
