# Generated by Django 3.1 on 2020-12-06 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_auto_20201125_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='coil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.cut_material'),
        ),
    ]
