# Generated by Django 3.1 on 2020-12-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_auto_20201206_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='coil_constant',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
