# Generated by Django 3.1 on 2020-12-14 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20201003_2158'),
        ('production', '0016_piece_coil_constant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OperatorPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(max_length=50)),
                ('machine_hourly_capacity', models.DecimalField(decimal_places=3, max_digits=6)),
                ('shift_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_capacity', models.DecimalField(decimal_places=3, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.machine')),
            ],
            options={
                'ordering': ['date', 'shift', 'machine'],
            },
        ),
    ]
