# Generated by Django 3.1 on 2020-12-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_operatorperformance_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shift',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
