# Generated by Django 3.1 on 2020-12-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_auto_20201217_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='prime_tonage',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piece',
            name='rejects_tonage',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piece',
            name='total_running_meters',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piece',
            name='total_tonage',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
