# Generated by Django 3.1 on 2020-12-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20201003_2158'),
        ('production', '0020_auto_20201217_0250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OperatorPerformance',
            new_name='Performance',
        ),
    ]
