# Generated by Django 3.1 on 2020-12-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_auto_20201217_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='total_production',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
