# Generated by Django 3.1 on 2021-01-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0022_performance_total_production'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coil',
        ),
        migrations.AddField(
            model_name='order',
            name='order_completed',
            field=models.BooleanField(default=False),
        ),
    ]
