# Generated by Django 3.1 on 2021-01-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0023_auto_20210103_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_tonage',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
