# Generated by Django 3.1 on 2021-01-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0024_order_order_tonage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='work_order_number',
            field=models.CharField(default='UBL', max_length=50),
            preserve_default=False,
        ),
    ]
