# Generated by Django 3.1 on 2021-01-15 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0026_standardmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='status',
            field=models.CharField(choices=[('Tranferred', 'Transferred'), ('Not Transferred', 'Not Transferred')], default='Not Transferred', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='standardmaterial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 17, 32, 19, 510936)),
        ),
    ]
