# Generated by Django 3.1 on 2021-01-15 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0027_auto_20210115_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='transferred_pieces',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='standardmaterial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 17, 44, 41, 148329)),
        ),
    ]
