# Generated by Django 3.1 on 2021-01-17 10:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20201003_2158'),
        ('production', '0028_auto_20210115_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManpowerPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(max_length=50)),
                ('operator', models.CharField(max_length=50)),
                ('helpers', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.machine')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shift_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='standardmaterial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 13, 39, 6, 521125)),
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(max_length=50)),
                ('production_type', models.CharField(choices=[('Work Order', 'Work Order'), ('Standard', 'Standard')], max_length=50)),
                ('colour', models.CharField(choices=[('Dark Green', 'Dark Green'), ('Potters Clay', 'Potters Clay'), ('Tile Red', 'Tile Red'), ('Brick Red', 'Brick Red'), ('Maroon', 'Maroon'), ('Zincal', 'Zincal'), ('Service Grey', 'Service Grey'), ('Galvanized Iron', 'Galvanized Iron'), ('Avocado', 'Avocado'), ('Lagoon', 'Lagoon'), ('Sky Blue', 'Sky Blue'), ('Charcoal Black', 'Charcoal Black'), ('Chocolate', 'Chocolate')], max_length=50)),
                ('finish', models.CharField(choices=[('Matt', 'Matt'), ('Plain', 'Plain')], max_length=50)),
                ('gauge', models.IntegerField(choices=[(32, 32), (30, 30), (28, 28), (26, 26), (24, 24), (22, 22), (20, 20)])),
                ('width', models.IntegerField(choices=[(1220, 1220), (975, 975), (960, 960), (487, 487), (462, 462), (320, 320)])),
                ('pieces', models.IntegerField(blank=True)),
                ('tonage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('ManpowerPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.manpowerplan')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.machine')),
            ],
        ),
    ]
