# Generated by Django 3.1 on 2021-01-21 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0029_auto_20210117_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardmaterial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 14, 16, 0, 481038)),
        ),
    ]
