# Generated by Django 3.1 on 2021-02-05 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0030_auto_20210121_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplan',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], max_length=50),
        ),
        migrations.AlterField(
            model_name='standardmaterial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 21, 1, 16, 663677)),
        ),
    ]
