# Generated by Django 3.1 on 2021-02-06 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0031_auto_20210205_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionplan',
            old_name='ManpowerPlan',
            new_name='man_power',
        ),
        migrations.AddField(
            model_name='productionplan',
            name='order_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='standardmaterial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 15, 9, 52, 690613)),
        ),
    ]
