# Generated by Django 3.1 on 2021-02-21 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0034_auto_20210221_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardmaterial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 21, 18, 2, 44, 53256)),
        ),
    ]
