# Generated by Django 3.1.7 on 2021-03-06 16:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0036_auto_20210302_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpowerplan',
            name='author',
            field=models.ForeignKey(default=1, limit_choices_to={'groups__name': 'Operators'}, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='standardmaterial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 19, 34, 39, 65980)),
        ),
    ]
