# Generated by Django 3.1.7 on 2021-03-06 16:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0037_auto_20210306_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manpowerplan',
            name='author',
        ),
        migrations.AlterField(
            model_name='manpowerplan',
            name='operator',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Operator'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='standardmaterial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 19, 37, 43, 386342)),
        ),
    ]
