# Generated by Django 3.1.7 on 2021-03-06 16:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0038_auto_20210306_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manpowerplan',
            name='operator',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='standardmaterial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 19, 43, 8, 41071)),
        ),
        migrations.CreateModel(
            name='ProdutionTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.section')),
            ],
        ),
    ]
