# Generated by Django 3.1.7 on 2021-03-06 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0039_auto_20210306_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardmaterial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 19, 46, 34, 113829)),
        ),
    ]
