# Generated by Django 3.1 on 2021-03-10 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0040_auto_20210306_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardmaterial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 12, 28, 57, 635566)),
        ),
    ]
