# Generated by Django 3.1 on 2021-03-13 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0045_auto_20210313_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardmaterial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 18, 30, 15, 486139)),
        ),
    ]
