# Generated by Django 3.1.7 on 2021-03-15 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0047_auto_20210313_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardmaterial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 14, 26, 11, 624360)),
        ),
    ]
