# Generated by Django 3.1 on 2021-04-17 08:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0048_auto_20210315_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardmaterial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 11, 46, 56, 291491)),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.section')),
            ],
        ),
    ]
