# Generated by Django 3.1 on 2021-04-17 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0050_auto_20210417_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='week_day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='standardmaterial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 12, 2, 51, 711181)),
        ),
    ]
