# Generated by Django 3.1 on 2021-04-17 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0051_auto_20210417_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='day',
            field=models.CharField(blank=True, choices=[('Week day', 'Week day'), ('Weekend', 'Weekend')], max_length=25),
        ),
        migrations.AlterField(
            model_name='standardmaterial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 12, 7, 17, 862049)),
        ),
    ]
