# Generated by Django 3.1 on 2021-04-17 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0052_auto_20210417_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='week_day',
        ),
        migrations.AlterField(
            model_name='standardmaterial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 12, 10, 1, 788622)),
        ),
    ]
