# Generated by Django 3.1.1 on 2020-10-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('hire_date', models.DateField()),
                ('photo', models.ImageField(blank=True, upload_to='photos/accounts/employee/%Y/%m/%d/')),
                ('department', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('employee_code', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
                ('contact', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['-first_name', '-section', 'job_title'],
            },
        ),
    ]
