# Generated by Django 3.1.1 on 2020-10-11 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0002_auto_20201003_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coil_parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coil_colour', models.CharField(max_length=50)),
                ('coil_colour_type', models.CharField(max_length=50)),
                ('coil_gauge', models.IntegerField()),
                ('coil_thickness', models.IntegerField()),
                ('coil_width', models.IntegerField()),
                ('coil_constant', models.IntegerField()),
            ],
            options={
                'ordering': ['coil_colour_type', 'coil_colour'],
            },
        ),
        migrations.CreateModel(
            name='Profile_machines_matching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=50)),
                ('producing_machine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.machine')),
            ],
            options={
                'ordering': ['producing_machine'],
            },
        ),
    ]
