# Generated by Django 3.1.1 on 2020-10-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coil_parameters',
            name='coil_finish',
            field=models.CharField(default='plain', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile_machines_matching',
            name='profile',
            field=models.CharField(choices=[('Covermax', 'Covermax'), ('Maxcover', 'Maxcover'), ('IT4', 'IT4'), ('Tekdek', 'Tekdek'), ('Versatile', 'Versatile'), ('Romantile', 'Romantile'), ('Normal Corrugation', 'Normal Corrugation'), ('Plain Sheet', 'Plain Sheet'), ('Normal Ridge', 'Normal Ridge'), ('Versatile Ridge', 'Versatile Ridge'), ('Romantile Ridge', 'Romantile Ridge')], max_length=50),
        ),
    ]
