# Generated by Django 3.1.1 on 2020-10-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_auto_20201011_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='coil_parameters',
            name='coil_number',
            field=models.CharField(default=123213, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coil_parameters',
            name='coil_finish',
            field=models.CharField(max_length=50),
        ),
    ]
