# Generated by Django 3.1.1 on 2020-10-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_auto_20201019_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coil_parameters',
            name='coil_number',
        ),
    ]
