# Generated by Django 3.1 on 2020-12-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0004_remove_coil_parameters_coil_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coil_parameters',
            name='coil_thickness',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
