# Generated by Django 3.1 on 2020-12-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0005_auto_20201206_0803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coil_parameters',
            options={'ordering': ['coil_type', 'coil_gauge', 'coil_finish']},
        ),
        migrations.RenameField(
            model_name='coil_parameters',
            old_name='coil_colour',
            new_name='coil_type',
        ),
        migrations.RemoveField(
            model_name='coil_parameters',
            name='coil_colour_type',
        ),
        migrations.AlterField(
            model_name='coil_parameters',
            name='coil_finish',
            field=models.CharField(choices=[('Matt', 'Matt'), ('Plain', 'Plain')], max_length=50),
        ),
    ]
