# Generated by Django 3.1 on 2020-12-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0006_auto_20201213_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconsiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coil_number', models.CharField(max_length=50)),
                ('initial_mass', models.IntegerField()),
                ('final_mass', models.IntegerField()),
                ('produced_mass', models.IntegerField()),
                ('initial_running_meters', models.IntegerField()),
                ('produced_running_meters', models.IntegerField()),
                ('mass_gain', models.IntegerField()),
                ('running_meters_gain', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='coil_parameters',
            name='coil_type',
            field=models.CharField(choices=[('HRC', 'HRC'), ('PPAZ', 'PPAZ'), ('AZ', 'AZ'), ('WIRE', 'WIRE')], max_length=50),
        ),
    ]
