# Generated by Django 3.1 on 2020-12-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0007_auto_20201214_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coil_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coil_type', models.CharField(choices=[('HRC', 'HRC'), ('PPAZ', 'PPAZ'), ('AZ', 'AZ'), ('WIRE', 'WIRE')], max_length=50)),
                ('coil_colour', models.CharField(choices=[('Dark Green', 'Dark Green'), ('Potters Clay', 'Potters Clay'), ('Tile Red', 'Tile Red'), ('Brick Red', 'Brick Red'), ('Maroon', 'Maroon'), ('Zincal', 'Zincal'), ('Service Grey', 'Service Grey'), ('Galvanized Iron', 'Galvanized Iron'), ('Avocado', 'Avocado'), ('Lagoon', 'Lagoon'), ('Sky Blue', 'Sky Blue'), ('Charcoal Black', 'Charcoal Black'), ('Chocolate', 'Chocolate')], max_length=50)),
                ('coil_finish', models.CharField(choices=[('Matt', 'Matt'), ('Plain', 'Plain')], max_length=50)),
            ],
        ),
    ]
