# Generated by Django 3.1 on 2020-12-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0008_coil_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconsiliation',
            name='coil_colour',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconsiliation',
            name='coil_finish',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconsiliation',
            name='coil_gauge',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconsiliation',
            name='coil_width',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
