# Generated by Django 3.1 on 2020-12-18 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0009_auto_20201218_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coil_number', models.CharField(max_length=50)),
                ('coil_gauge', models.IntegerField()),
                ('coil_width', models.IntegerField()),
                ('coil_colour', models.CharField(max_length=50)),
                ('coil_finish', models.CharField(max_length=10)),
                ('initial_mass', models.IntegerField()),
                ('initial_running_meters', models.IntegerField()),
                ('date_received', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['coil_colour', 'coil_finish', 'coil_gauge', '-coil_width'],
            },
        ),
    ]
