# Generated by Django 3.1 on 2021-01-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0011_coil_final_mass'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardMaterialParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(choices=[('Covermax', 'Covermax'), ('Maxcover', 'Maxcover'), ('IT4', 'IT4'), ('Tekdek', 'Tekdek'), ('Versatile', 'Versatile'), ('Romantile', 'Romantile'), ('Normal Corrugation', 'Normal Corrugation'), ('Plain Sheet', 'Plain Sheet'), ('Normal Ridge', 'Normal Ridge'), ('Versatile Ridge', 'Versatile Ridge'), ('Romantile Ridge', 'Romantile Ridge')], max_length=50)),
                ('gauge', models.IntegerField(choices=[(32, 32), (30, 30), (28, 28), (26, 26), (24, 24), (22, 22), (20, 20)])),
                ('has_standard_width', models.BooleanField(default=False)),
                ('standard_width', models.IntegerField(choices=[(1220, 1220), (975, 975), (960, 960), (487, 487), (462, 462), (320, 320)])),
                ('has_standard_length', models.BooleanField(default=False)),
                ('standard_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
    ]
