# Generated by Django 3.1 on 2021-01-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0012_standardmaterialparameters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coil',
        ),
    ]
