# Generated by Django 3.1.7 on 2021-03-02 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0013_delete_coil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile_machines_matching',
            options={'ordering': ['machine']},
        ),
        migrations.RenameField(
            model_name='profile_machines_matching',
            old_name='producing_machine',
            new_name='machine',
        ),
    ]
