# Generated by Django 3.1 on 2021-03-10 09:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0014_auto_20210302_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconsiliation',
            name='finish_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconsiliation',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 10, 9, 29, 39, 70882, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
