# Generated by Django 3.1.1 on 2020-10-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_hourly_capacity',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
